// Planlamasyon içine gömülü resmî imar hizmetleri kataloğu.
// Kaynak: planlamasyon_belediye_imar_katalogu.json
// Link bulunması otomatik API erişimi veya yapılaşma hakkı doğrulaması anlamına gelmez.

export const MUNICIPALITY_CATALOG_VERSION = "2026-08-23";
export const MUNICIPALITY_CATALOG_STATS = Object.freeze({
  "recordCount": 117,
  "municipalityOrInstitutionCount": 102,
  "provinceCount": 29,
  "directProvinceCount": 29,
  "directDistrictPairCount": 94,
  "routingProvinceCount": 81,
  "nationwideRouting": true,
  "routingMode": "dynamic-official-link-routing",
  "nationalRecordCount": 5,
  "municipalRecordCount": 112,
  "machineReadableCandidateCount": 0
});
export const MUNICIPALITY_CATALOG = Object.freeze([
  {
    "id": "adana-saricam-belediyesi-e-imar",
    "province": "Adana",
    "district": "Sarıçam",
    "scope": "district",
    "authority": "Sarıçam Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/saricam-belediyesi-eimar-8838",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "adana-seyhan-belediyesi-e-imar",
    "province": "Adana",
    "district": "Seyhan",
    "scope": "district",
    "authority": "Seyhan Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/seyhan-belediyesi-e-imar-8746",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "adana-yuregir-belediyesi-e-imar",
    "province": "Adana",
    "district": "Yüreğir",
    "scope": "district",
    "authority": "Yüreğir Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/yuregir-belediyesi-eimar-7872",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "adana-cukurova-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Adana",
    "district": "Çukurova",
    "scope": "district",
    "authority": "Çukurova Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/cukurova-belediyesi-imar-durum-sorgulama-v3",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "amasya-amasya-belediyesi-e-imar",
    "province": "Amasya",
    "district": "Amasya",
    "scope": "district",
    "authority": "Amasya Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/amasya-belediyesi-eimar-8348",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-ankara-buyuksehir-belediyesi-e-imar",
    "province": "Ankara",
    "district": "*",
    "scope": "province",
    "authority": "Ankara Büyükşehir Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/abb-eimar-8705",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-etimesgut-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Etimesgut",
    "scope": "district",
    "authority": "Etimesgut Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/etimesgut-belediyesi-eimar-8970",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-golbasi-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Gölbaşı",
    "scope": "district",
    "authority": "Gölbaşı Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/golbasi-belediyesi-eimar-8828",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-kecioren-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Keçiören",
    "scope": "district",
    "authority": "Keçiören Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/kecioren-belediyesi-eimar-8093",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-kecioren-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Ankara",
    "district": "Keçiören",
    "scope": "district",
    "authority": "Keçiören Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/kecioren-belediyesi-kecioren-belediyesi-imar-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-pursaklar-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Pursaklar",
    "scope": "district",
    "authority": "Pursaklar Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/imar-yonetim-sistemi-6123",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-sincan-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Sincan",
    "scope": "district",
    "authority": "Sincan Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/sincan-belediyesi-eimar-8569",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-yenimahalle-belediyesi-e-imar",
    "province": "Ankara",
    "district": "Yenimahalle",
    "scope": "district",
    "authority": "Yenimahalle Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/yenimahalle-belediyesi-e-imar-8750",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ankara-cankaya-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Ankara",
    "district": "Çankaya",
    "scope": "district",
    "authority": "Çankaya Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/cankaya-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "antalya-alanya-belediyesi-e-imar",
    "province": "Antalya",
    "district": "Alanya",
    "scope": "district",
    "authority": "Alanya Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6778",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "aydin-efeler-belediyesi-e-imar",
    "province": "Aydın",
    "district": "Efeler",
    "scope": "district",
    "authority": "Efeler Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/efeler-belediyesi-eimar-8347",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "aydin-soke-belediyesi-e-imar",
    "province": "Aydın",
    "district": "Söke",
    "scope": "district",
    "authority": "Söke Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/soke-belediyesi-eimar-8626",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bilecik-bilecik-belediyesi-e-imar",
    "province": "Bilecik",
    "district": "Bilecik",
    "scope": "district",
    "authority": "Bilecik Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/bilecik-belediyesi-eimar-7988",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-karacabey-belediyesi-e-imar",
    "province": "Bursa",
    "district": "Karacabey",
    "scope": "district",
    "authority": "Karacabey Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/karacabey-belediyesi-eimar-8446",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-mudanya-belediyesi-e-imar",
    "province": "Bursa",
    "district": "Mudanya",
    "scope": "district",
    "authority": "Mudanya Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/mudanya-belediyesi-eimar-7794",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-nilufer-belediyesi-e-imar",
    "province": "Bursa",
    "district": "Nilüfer",
    "scope": "district",
    "authority": "Nilüfer Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6403",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-orhangazi-belediyesi-e-imar",
    "province": "Bursa",
    "district": "Orhangazi",
    "scope": "district",
    "authority": "Orhangazi Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7334",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-inegol-belediyesi-e-imar",
    "province": "Bursa",
    "district": "İnegöl",
    "scope": "district",
    "authority": "İnegöl Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/inegol-belediyesi-eimar-8153",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "bursa-inegol-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Bursa",
    "district": "İnegöl",
    "scope": "district",
    "authority": "İnegöl Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/inegol-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "gaziantep-sahinbey-belediyesi-e-imar",
    "province": "Gaziantep",
    "district": "Şahinbey",
    "scope": "district",
    "authority": "Şahinbey Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/belnet-6436",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "gaziantep-sahinbey-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Gaziantep",
    "district": "Şahinbey",
    "scope": "district",
    "authority": "Şahinbey Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/sahinbey-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "gaziantep-sehitkamil-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Gaziantep",
    "district": "Şehitkamil",
    "scope": "district",
    "authority": "Şehitkamil Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/sehitkamil-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "hatay-antakya-belediyesi-e-imar",
    "province": "Hatay",
    "district": "Antakya",
    "scope": "district",
    "authority": "Antakya Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/antakya-belediyesi-eimar-8671",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "hatay-iskenderun-belediyesi-e-imar",
    "province": "Hatay",
    "district": "İskenderun",
    "scope": "district",
    "authority": "İskenderun Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/iskenderun-belediyesi-eimar-8207",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kahramanmaras-afsin-belediyesi-e-imar",
    "province": "Kahramanmaraş",
    "district": "Afşin",
    "scope": "district",
    "authority": "Afşin Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/afsin-belediyesi-eimar-8613",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kahramanmaras-goksun-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Kahramanmaraş",
    "district": "Göksun",
    "scope": "district",
    "authority": "Göksun Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/goksun-belediyesi-imar-durum-sorgulama-v3",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kahramanmaras-onikisubat-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "Kahramanmaraş",
    "district": "Onikişubat",
    "scope": "district",
    "authority": "Onikişubat Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/onikisubat-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kahramanmaras-onikisubat-belediyesi-e-imar",
    "province": "Kahramanmaraş",
    "district": "Onikişubat",
    "scope": "district",
    "authority": "Onikişubat Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/onikisubat-belediyesi-eimar-8308",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kastamonu-abana-belediyesi-e-imar",
    "province": "Kastamonu",
    "district": "Abana",
    "scope": "district",
    "authority": "Abana Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/abana-belediyesi-e-imar-7534",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kayseri-melikgazi-belediyesi-e-imar",
    "province": "Kayseri",
    "district": "Melikgazi",
    "scope": "district",
    "authority": "Melikgazi Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7311",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-dilovasi-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Dilovası",
    "scope": "district",
    "authority": "Dilovası Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/dilovasi-belediyesi-eimar-8595",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-gebze-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Gebze",
    "scope": "district",
    "authority": "Gebze Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6330",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-golcuk-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Gölcük",
    "scope": "district",
    "authority": "Gölcük Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/golcuk-belediyesi-eimar-7748",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-kartepe-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Kartepe",
    "scope": "district",
    "authority": "Kartepe Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/kartepe-belediyesi-eimar-8775",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-korfez-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Körfez",
    "scope": "district",
    "authority": "Körfez Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7008",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-cayirova-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "Çayırova",
    "scope": "district",
    "authority": "Çayırova Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/cayirova-belediyesi-eimar-8528",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "kocaeli-izmit-belediyesi-e-imar",
    "province": "Kocaeli",
    "district": "İzmit",
    "scope": "district",
    "authority": "İzmit Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/izmit-belediyesi-eimar-7922",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "konya-ilgin-belediyesi-e-imar",
    "province": "Konya",
    "district": "Ilgın",
    "scope": "district",
    "authority": "Ilgın Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7210",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "konya-selcuklu-belediyesi-e-imar",
    "province": "Konya",
    "district": "Selçuklu",
    "scope": "district",
    "authority": "Selçuklu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/selcuklu-belediyesi-eimar-8942",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "malatya-malatya-buyuksehir-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Malatya",
    "district": "*",
    "scope": "province",
    "authority": "Malatya Büyükşehir Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/malatya-buyuksehir-belediyesi-imar-durum-sorgulama-v3",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "malatya-yesilyurt-belediyesi-e-imar",
    "province": "Malatya",
    "district": "Yeşilyurt",
    "scope": "district",
    "authority": "Yeşilyurt Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/imar-yonetim-sistemi-6279",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "manisa-salihli-belediyesi-e-imar",
    "province": "Manisa",
    "district": "Salihli",
    "scope": "district",
    "authority": "Salihli Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/salihli-belediyesi-eimar-8231",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "manisa-soma-belediyesi-e-imar",
    "province": "Manisa",
    "district": "Soma",
    "scope": "district",
    "authority": "Soma Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7465",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "manisa-turgutlu-belediyesi-e-imar",
    "province": "Manisa",
    "district": "Turgutlu",
    "scope": "district",
    "authority": "Turgutlu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/turgutlu-belediyesi-e-imar-7621",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "manisa-sehzadeler-belediyesi-e-imar",
    "province": "Manisa",
    "district": "Şehzadeler",
    "scope": "district",
    "authority": "Şehzadeler Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6362",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "mugla-bodrum-belediyesi-e-imar",
    "province": "Muğla",
    "district": "Bodrum",
    "scope": "district",
    "authority": "Bodrum Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6781",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "mugla-fethiye-belediyesi-e-imar",
    "province": "Muğla",
    "district": "Fethiye",
    "scope": "district",
    "authority": "Fethiye Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/fethiye-belediyesi-eimar-8710",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "mugla-koycegiz-belediyesi-e-imar",
    "province": "Muğla",
    "district": "Köyceğiz",
    "scope": "district",
    "authority": "Köyceğiz Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/koycegiz-belediysi-eimar-7935",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "mugla-mentese-belediyesi-e-imar",
    "province": "Muğla",
    "district": "Menteşe",
    "scope": "district",
    "authority": "Menteşe Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/mentese-belediyesi-eimar-7934",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "nigde-nigde-belediyesi-e-imar",
    "province": "Niğde",
    "district": "Niğde",
    "scope": "district",
    "authority": "Niğde Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/nigde-belediyesi-eimar-8140",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ordu-altinordu-belediyesi-e-imar",
    "province": "Ordu",
    "district": "Altınordu",
    "scope": "district",
    "authority": "Altınordu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7209",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ordu-altinordu-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Ordu",
    "district": "Altınordu",
    "scope": "district",
    "authority": "Altınordu Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/altinordu-belediyesi-imar-durum-sorgulama-v3",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "ordu-unye-belediyesi-e-imar",
    "province": "Ordu",
    "district": "Ünye",
    "scope": "district",
    "authority": "Ünye Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7419",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "sakarya-adapazari-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Sakarya",
    "district": "Adapazarı",
    "scope": "district",
    "authority": "Adapazarı Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/adapazari-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "sakarya-hendek-belediyesi-e-imar",
    "province": "Sakarya",
    "district": "Hendek",
    "scope": "district",
    "authority": "Hendek Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/hendek-belediyesi-eimar-8965",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "sakarya-karasu-belediyesi-e-imar",
    "province": "Sakarya",
    "district": "Karasu",
    "scope": "district",
    "authority": "Karasu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7022",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "sakarya-sapanca-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Sakarya",
    "district": "Sapanca",
    "scope": "district",
    "authority": "Sapanca Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/sapanca-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "sakarya-serdivan-belediyesi-e-imar",
    "province": "Sakarya",
    "district": "Serdivan",
    "scope": "district",
    "authority": "Serdivan Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/serdivan-belediyesi-ebelediye-7940",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "tekirdag-ergene-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "Tekirdağ",
    "district": "Ergene",
    "scope": "district",
    "authority": "Ergene Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/ergene-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "tekirdag-ergene-belediyesi-e-imar",
    "province": "Tekirdağ",
    "district": "Ergene",
    "scope": "district",
    "authority": "Ergene Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/ergene-belediyesi-e-imar-7535",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "tekirdag-ergene-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Tekirdağ",
    "district": "Ergene",
    "scope": "district",
    "authority": "Ergene Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/ergene-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "tekirdag-tekirdag-buyuksehir-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "Tekirdağ",
    "district": "*",
    "scope": "province",
    "authority": "Tekirdağ Büyükşehir Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/tekirdag-buyuksehir-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "tekirdag-corlu-belediyesi-e-imar",
    "province": "Tekirdağ",
    "district": "Çorlu",
    "scope": "district",
    "authority": "Çorlu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/corlu-belediyesi-eimar-8230",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "trabzon-akcaabat-belediyesi-e-imar",
    "province": "Trabzon",
    "district": "Akçaabat",
    "scope": "district",
    "authority": "Akçaabat Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6655",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "trabzon-ortahisar-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "Trabzon",
    "district": "Ortahisar",
    "scope": "district",
    "authority": "Ortahisar Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/trabzon-ortahisar-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "turkiye-tucbs-ulusal-cografi-bilgi-platformu",
    "province": "Türkiye",
    "district": null,
    "scope": "national",
    "authority": "TUCBS",
    "title": "Ulusal Coğrafi Bilgi Platformu",
    "url": "https://tucbs.gov.tr/",
    "sourceType": "Ulusal resmî portal",
    "authentication": "Bazı katmanlar",
    "accessMode": "public-portal",
    "kind": "national-geodata",
    "machineReadableCandidate": false,
    "note": "Açık coğrafi katmanlar ve servis/metaveri erişimi.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "turkiye-tapu-ve-kadastro-genel-mudurlugu-parsel-sorgu",
    "province": "Türkiye",
    "district": null,
    "scope": "national",
    "authority": "Tapu ve Kadastro Genel Müdürlüğü",
    "title": "Parsel Sorgu",
    "url": "https://parselsorgu.tkgm.gov.tr/",
    "sourceType": "Ulusal resmî portal",
    "authentication": "Hayır/servise göre",
    "accessMode": "public-portal",
    "kind": "cadastre",
    "machineReadableCandidate": false,
    "note": "Kadastro/parsel konumu ve temel bilgiler için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "turkiye-e-devlet-kapisi-belediye-hizmetleri-katalogu",
    "province": "Türkiye",
    "district": null,
    "scope": "national",
    "authority": "e-Devlet Kapısı",
    "title": "Belediye Hizmetleri Kataloğu",
    "url": "https://www.turkiye.gov.tr/belediyeler",
    "sourceType": "Ulusal resmî katalog",
    "authentication": "Hayır",
    "accessMode": "public-portal",
    "kind": "national-directory",
    "machineReadableCandidate": false,
    "note": "e-Devlet'teki belediye hizmetlerini il ve belediye bazında bulmak için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "turkiye-cevre-sehircilik-ve-iklim-degisikligi-bakanligi-e-plan-otomasyon-sistemleri",
    "province": "Türkiye",
    "district": null,
    "scope": "national",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "title": "e-Plan Otomasyon Sistemleri",
    "url": "https://eplan.csb.gov.tr/",
    "sourceType": "Ulusal resmî portal",
    "authentication": "Bazı bölümler",
    "accessMode": "public-portal",
    "kind": "national-portal",
    "machineReadableCandidate": false,
    "note": "Askıdaki planlar, yürürlükteki planlar ve imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "turkiye-cevre-sehircilik-ve-iklim-degisikligi-bakanligi-e-plan-imar-durumu",
    "province": "Türkiye",
    "district": null,
    "scope": "national",
    "authority": "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
    "title": "e-Plan İmar Durumu",
    "url": "https://eplan.csb.gov.tr/e-plan/html/imarDurumu.html",
    "sourceType": "Ulusal resmî portal",
    "authentication": "Değişebilir",
    "accessMode": "public-portal",
    "kind": "national-portal",
    "machineReadableCandidate": false,
    "note": "Parsel bazlı imar durumu ekranı.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "usak-usak-belediyesi-e-imar",
    "province": "Uşak",
    "district": "Uşak",
    "scope": "district",
    "authority": "Uşak Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/imar-yonetim-sistemi-6244",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "van-van-buyuksehir-belediyesi-imar-durumu-sorgulama",
    "province": "Van",
    "district": "*",
    "scope": "province",
    "authority": "Van Büyükşehir Belediyesi",
    "title": "İmar Durumu Sorgulama",
    "url": "https://cbs.van.bel.tr/imardurumu/",
    "sourceType": "Belediye resmî CBS",
    "authentication": "Hayır/servise göre",
    "accessMode": "public-portal",
    "kind": "municipality-geodata",
    "machineReadableCandidate": false,
    "note": "Doğrudan belediye CBS/imar ekranı.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "yalova-yalova-belediyesi-e-imar",
    "province": "Yalova",
    "district": "Yalova",
    "scope": "district",
    "authority": "Yalova Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/yalova-belediyesi-eimar-8943",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "yozgat-sorgun-belediyesi-e-imar",
    "province": "Yozgat",
    "district": "Sorgun",
    "scope": "district",
    "authority": "Sorgun Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/sorgun-belediyesi-eimar-8982",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "corum-corum-belediyesi-e-imar",
    "province": "Çorum",
    "district": "Çorum",
    "scope": "district",
    "authority": "Çorum Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6506",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-arnavutkoy-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "İstanbul",
    "district": "Arnavutköy",
    "scope": "district",
    "authority": "Arnavutköy Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/arnavutkoy-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-arnavutkoy-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Arnavutköy",
    "scope": "district",
    "authority": "Arnavutköy Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/arnavutkoy-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-bahcelievler-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "İstanbul",
    "district": "Bahçelievler",
    "scope": "district",
    "authority": "Bahçelievler Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/bahcelievler-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-bahcelievler-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Bahçelievler",
    "scope": "district",
    "authority": "Bahçelievler Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6406",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-bahcelievler-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Bahçelievler",
    "scope": "district",
    "authority": "Bahçelievler Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/bahcelievler-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-bagcilar-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Bağcılar",
    "scope": "district",
    "authority": "Bağcılar Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/bagcilar-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-beylikduzu-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Beylikdüzü",
    "scope": "district",
    "authority": "Beylikdüzü Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/beylikduzu-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-beyoglu-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Beyoğlu",
    "scope": "district",
    "authority": "Beyoğlu Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/beyoglu-belediyesi-e-imar-7620",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-buyukcekmece-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "İstanbul",
    "district": "Büyükçekmece",
    "scope": "district",
    "authority": "Büyükçekmece Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/buyukcekmece-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-buyukcekmece-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Büyükçekmece",
    "scope": "district",
    "authority": "Büyükçekmece Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/buyukcekmece-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-esenyurt-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Esenyurt",
    "scope": "district",
    "authority": "Esenyurt Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/esenyurt-belediyesi-eimar-8586",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-esenyurt-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Esenyurt",
    "scope": "district",
    "authority": "Esenyurt Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/esenyurt-belediyesi-imar-durum-sorgulama-v3",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-eyupsultan-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Eyüpsultan",
    "scope": "district",
    "authority": "Eyüpsultan Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/eyupsultan-belediyesi-e-imar-7543",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-fatih-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Fatih",
    "scope": "district",
    "authority": "Fatih Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7462",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-kucukcekmece-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Küçükçekmece",
    "scope": "district",
    "authority": "Küçükçekmece Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/kucukcekmece-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-maltepe-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Maltepe",
    "scope": "district",
    "authority": "Maltepe Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6457",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-pendik-belediyesi-askidaki-imar-plani-sorgulama",
    "province": "İstanbul",
    "district": "Pendik",
    "scope": "district",
    "authority": "Pendik Belediyesi",
    "title": "Askıdaki İmar Planı Sorgulama",
    "url": "https://www.turkiye.gov.tr/pendik-belediyesi-askidaki-imar-plani-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Plan ilan ve askı süreçleri için.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-pendik-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Pendik",
    "scope": "district",
    "authority": "Pendik Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/pendik-belediyesi-imar-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-sancaktepe-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Sancaktepe",
    "scope": "district",
    "authority": "Sancaktepe Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6435",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-sancaktepe-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Sancaktepe",
    "scope": "district",
    "authority": "Sancaktepe Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/sancaktepe-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-silivri-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Silivri",
    "scope": "district",
    "authority": "Silivri Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/silivri-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-sultanbeyli-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Sultanbeyli",
    "scope": "district",
    "authority": "Sultanbeyli Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7069",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-sultangazi-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Sultangazi",
    "scope": "district",
    "authority": "Sultangazi Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/belnet-6437",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-tuzla-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Tuzla",
    "scope": "district",
    "authority": "Tuzla Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/tuzla-belediyesi-eimar-8670",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-zeytinburnu-belediyesi-online-imar-durum-belgesi-basvurusu",
    "province": "İstanbul",
    "district": "Zeytinburnu",
    "scope": "district",
    "authority": "Zeytinburnu Belediyesi",
    "title": "Online İmar Durum Belgesi Başvurusu",
    "url": "https://www.turkiye.gov.tr/online-imar-durum-belgesi-basvurusu-5368",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "İmar durum belgesi başvurusu.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-cekmekoy-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Çekmeköy",
    "scope": "district",
    "authority": "Çekmeköy Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/cekmekoy-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-uskudar-belediyesi-e-imar",
    "province": "İstanbul",
    "district": "Üsküdar",
    "scope": "district",
    "authority": "Üsküdar Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/uskudar-belediyesi-eimar-8621",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "istanbul-sisli-belediyesi-imar-durum-bilgisi-sorgulama",
    "province": "İstanbul",
    "district": "Şişli",
    "scope": "district",
    "authority": "Şişli Belediyesi",
    "title": "İmar Durum Bilgisi Sorgulama",
    "url": "https://www.turkiye.gov.tr/sisli-belediyesi-imar-durum-sorgulama",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Hizmete göre",
    "accessMode": "official-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "Ada/parsel veya adresle resmî imar durumu sorgulama.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-bayrakli-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Bayraklı",
    "scope": "district",
    "authority": "Bayraklı Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6685",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-bergama-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Bergama",
    "scope": "district",
    "authority": "Bergama Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6404",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-bornova-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Bornova",
    "scope": "district",
    "authority": "Bornova Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/bornova-belediyesi-eimar-8297",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-buca-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Buca",
    "scope": "district",
    "authority": "Buca Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/buca-belediyesi-e-imar-6730",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-gaziemir-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Gaziemir",
    "scope": "district",
    "authority": "Gaziemir Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-7111",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-seferihisar-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Seferihisar",
    "scope": "district",
    "authority": "Seferihisar Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/seferihisar-belediyesi-eimar-7727",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-torbali-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Torbalı",
    "scope": "district",
    "authority": "Torbalı Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/torbali-belediyesi-eimar-8815",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-cesme-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Çeşme",
    "scope": "district",
    "authority": "Çeşme Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/cesme-belediyesi-e-imar-7595",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  },
  {
    "id": "izmir-odemis-belediyesi-e-imar",
    "province": "İzmir",
    "district": "Ödemiş",
    "scope": "district",
    "authority": "Ödemiş Belediyesi",
    "title": "e-İmar",
    "url": "https://www.turkiye.gov.tr/e-imar-6455",
    "sourceType": "e-Devlet belediye hizmeti",
    "authentication": "Çoğunlukla evet",
    "accessMode": "official-login-service",
    "kind": "municipality-portal",
    "machineReadableCandidate": false,
    "note": "e-Devlet oturumu gerekebilir; otomatik API değildir.",
    "verifiedAt": "2026-08-23"
  }
]);
